---
# docker compose -f pg-compose.yml up -d
#
# postgres shell
# docker compose -f pg-compose.yml exec pg-dev psql -U postgres

# run a day's sql
# docker compose -f pg-compose.yml exec pg-dev psql -U postgres -f /aoc/day1/day1.sql

services:
  pg-dev:
    image: 'postgres:17.0'
    ports:
      - '6543:5432'
    volumes:
      - './db-data/:/var/lib/postgresql/data/'
      - './sql/:/aoc/'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 25433:80
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: default_db
      PGADMIN_DEFAULT_PASSWORD: dev_password
      PGADMIN_DEFAULT_EMAIL: dev@lilcloud.dev
    depends_on:
      - pg-dev
    volumes:
      - './pgadmin-data/:/var/lib/pgadmin/'
